### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by vBlackOut** [warthog618/gpiod#25]
RequestLine returned error: invalid argument
Note that the WithPullUp option requires kernel V5.5 or later - check your kernel version.
exit status 1
pi@raspberrypi:~/go $ uname -a
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

my code

 l, err := c.RequestLine(offset,
		                     gpiod.WithPullUp,
	                             gpiod.WithEventBufferSize(1),
                                     gpiod.WithEventHandler(eventHandler))

 it's use WithEventBufferSize but d'ont work please send me a example

i have kernel 5.10 weird

**Comment by warthog618** [comment]
You are modifying the watcher example, correct?
That example will report that error whenever the kernel returns an invalid argument error, and is specific to that example code.
The only reason the options in that example can fail is if you have an old kernel, hence the error message.
But if you change the code then you may introduce other reasons for the error.  Weird right?
The kernel doesn't like one of your options, so what have you changed?
You removed the gpiod.WithBothEdges.  That option is necessary to select the line as an input and to specify which edges to detect - the default is none and to leave the line as-is.  The kernel requires the line to be explicitly selected as an input if you want to use edge detection.
So restore the WithBothEdges, or if you are only interested in rising or falling edges then use the corresponding option instead.

You also added the WithEventBufferSize(1) option, which is weird but should work.
Why WithEventBufferSize(1)?
Why do you want to change the buffer size at all, and why to 1?
This option influences (not directly controls) the size of the event buffer in the kernel, i.e. the number of event it can store while waiting for userspace (you) to deal  with previous events.  So the buffer is there to handle bursts of events.
The default is 16, and the option is generally there for extreme cases that need MORE buffering.
There is little point decreasing it - that just increases the chance of the kernel buffer overflowing and you losing events.

**Comment by vBlackOut** [comment]
I don't know but some request is made with latencies I would just like to remove it's latencies

**Comment by warthog618** [comment]
There is no latency to be removed via the GPIO API - there are no delays in there and any queuing is only to deal with userspace being too busy to handle events when they arrive.  Any latency you are seeing is most likely due to something else using CPU time.
The timestamps on the edge events indicate when the kernel first saw the event.  You can use those to determine where any latency/jitter is creeping in.
If there is no jitter in those timestamps then the latency is completely in userspace and you need to look at what other processes you have running and their relative priority, or there may be an issue in your go program that holds up the goroutine handling the events.
If there is jitter in those timestamps then either the kernel itself is busy dealing with something else or your input signal has jitter in it.
